[[achievements]]
id = 1
name = "Une personne formée"
description = "Il faut bien commencer quelque part ! à vous le NDA !"
trainings = 1
trainingsPerSecond = 0

[[achievements]]
id = 2
name = "Découverte de l'automatisation"
description = "Vous formez automatiquement 10 personnes par seconde"
trainings = 0
trainingsPerSecond = 10

[[achievements]]
id = 3
name = "30 personnes formées"
description = "On pourrait remplir une salle de classe avec vos anciens élèves"
trainings = 30
trainingsPerSecond = 0

[[achievements]]
id = 4
name = "100 personnes formées"
description = "CENT PATATES ? Ah non, cent apprenants"
trainings = 100
trainingsPerSecond = 0

[[achievements]]
id = 5
name = "200 personnes formées"
description = "Hey mais c'est que vous n'êtes plus un si petit formateur !"
trainings = 200
trainingsPerSecond = 0

[[achievements]]
id = 6
name = "365 personnes formées"
description = "Autant d'apprenants que de jours dans l'année, bravo !"
trainings = 365
trainingsPerSecond = 0

[[achievements]]
id = 7
name = "500 personnes formées"
description = "Bienvenue sur l'abonnement Orga !"
trainings = 500
trainingsPerSecond = 0

[[achievements]]
id = 8
name = "777 personnes formées"
description = "Chiffre porte bonheur faites un vœu !"
trainings = 777
trainingsPerSecond = 0

[[achievements]]
id = 9
name = "1500 personnes formées"
description = "Vous avez toujours rêvé d'avoir un KAM sur Digiforma ?"
trainings = 1500
trainingsPerSecond = 0

[[achievements]]
id = 10
name = "80 000 personnes formées"
description = "On pourrait remplir le stade de France avec vos apprenants, bravo !"
trainings = 80000
trainingsPerSecond = 0

[[achievements]]
id = 11
name = "522 228 personnes formées"
description = "Félicitations, vous avez formé toute la ville de Lyon !"
trainings = 522228
trainingsPerSecond = 0

[[achievements]]
id = 12
name = "14 07 1993 personnes formées"
description = "Autant d'apprenants que la date d'anniversaire de Jade, bravo !"
trainings = 14071993
trainingsPerSecond = 0

[[achievements]]
id = 13
name = "68 millions de personnes formées"
description = "Félicitations, vous avez formé toute la France !"
trainings = 68000000
trainingsPerSecond = 0

[[achievements]]
id = 14
name = "8 milliards de personnes formées"
description = "Vous avez formé la terre entière ! On passe aux martiens ?"
trainings = 8000000000
trainingsPerSecond = 0
