[[Collaborateurs]]
name = "Régis"
description = "Il est sympa mais un peu désorganisé."
buyableTips = ["Bien joué ! Vous avez assez d'argent pour débloquer Régis, cliquez dessus !"]

[[Collaborateurs]]
name = "Pétronille"
description = "Les jeunes avec leur TokTok savent utiliser les ordinateurs."
requirement = ["Digiforma"]

[[Collaborateurs]]
name = "Kat Jépété"
description = "L'intelligence artificielle c'est son dada."
requirement = ["Multi-Centres"]

[["Écosystème"]]
name = "Formalerte"
description = "Votre outils de veille du quotidien"
requirement = ["Digiforma"]

[["Écosystème"]]
name = "Digiformag"
description = "LE journal de la formation pro en France"
requirement = ["Régis"]

[["Écosystème"]]
name = "Digiformag 2"
description = "Gratuit et de qualité pour tous les OF de France"
requirement = ["Digiformag"]

[["Écosystème"]]
name = "Digiformag 3"
description = "Des articles de fond pour les professionnels de la formation"
requirement = ["Digiformag 2"]

[["Écosystème"]]
name = "Digiformag 4"
description = "Dans leur plus belles formes, merci aux illustratrices et aux illustrateurs"
requirement = ["Digiformag 3"]

[["Écosystème"]]
name = "Digiformag 5"
description = "On en est fiers, et on espère que vous aussi"
requirement = ["Digiformag 5"]

[["Écosystème"]]
name = "OF Connect"
description = "Comme un groupe whatsapp entre amis, mais pour le monde de la formation"
requirement = ["Formalerte"]

[["Écosystème"]]
name = "OC Connect"
description = "C'est quoi déjà exactement un certificateur ?"
requirement = ["Référencement RS"]

[[Outils]]
name = "Excel"
description = "Je suis expert, j'ai eu un cours d'excel au lycée"
requirement = ["Régis"]

[[Outils]]
name = "Digiforma"
description = "Est-ce qu'il faut encore le présenter ?"
requirement = ["Excel"]

[["Modalités"]]
name = "Salle de classe"
description = "C'est comme une salle de réunion mais avec des tables"
requirement= ["Régis"]
tips = ["Vous pouvez de nouveau débloquer des améliorations. Continuez de cliquer pour débloquer la Galaxy Digiforma et devenir le plus gros des OF !"]

[["Modalités"]]
name = "Amphithéâtre"
description = "Au fond, réveillez-vous s'il vous plaît"
requirement = ["Salle de classe"]

[["Modalités"]]
name = "MOOC"
description = "Règle numéro 1 : tout le monde doit montrer son chien à la caméra, c'est la pet tax"
requirement = ["Visio", "OF Connect"]

[["Modalités"]]
name = "Réalité Virtuelle"
description = "On a l'air bizarre mais on apprend bien"
requirement = ["MOOC", "Signature Électronique", "Digiformag"]

[["Fonctionnalités"]]
name = "Paiement en ligne"
description = "Rapide, fiable et sécurisé"
requirement = ["Digiforma"]

[["Fonctionnalités"]]
name = "Signature Électronique"
description = "Pour les OPCO un peu trop tatillons"
requirement = ["Digiforma"]

[["Fonctionnalités"]]
name = "Visio"
description = "Et tout le monde met sa caméra s'il vous plaît"
requirement = ["Digiforma"]

[["Fonctionnalités"]]
name = "Multi-Centres"
description = "Avec un tiret et un S s'il vous plaît"
requirement = ["Digiforma"]

[["Fonctionnalités"]]
name = "Certification Numérique"
description = "C'est comme un diplôme mais on a pas le droit de les appeler comme ça"
requirement = ["Digiforma"]

[["Fonctionnalités"]]
name = "Marketplace"
description = "Rien de mieux que de faire ses courses sur Digiforma"
requirement = ["Digiforma"]

[[Certifications]]
name = "Qualiopi"
description = "Avec Digiforma c'est facile, mais on oublie pas sa veille"
requirement = ["Digiforma", "Formalerte"]

[[Certifications]]
name = "Audit de surveillance"
description = "Il faut pas se laisser aller"
requirement = ["Qualiopi"]

[[Certifications]]
name = "Audit de surveillance 2"
description = "Encore ? Mais on vient juste de passer le premier !"
requirement = ["Audit de surveillance"]

[[Certifications]]
name = "Référencement RS"
description = "Claire a l'aide, je sais pas ce que c'est"
requirement = ["Audit de surveillance 2"]

[["Récompenses"]]
name = "Médaille en bronze"
description = "Ne la mangez pas, c'est pour la déco"
requirement = ["OC Connect", "Réalité Virtuelle"]

[["Récompenses"]]
name = "Médaille en argent"
description = "Plus qu'un pas"
requirement = ["Médaille en bronze"]

[["Récompenses"]]
name = "Trophée de la formation"
description = "Un trophée pour les gouverner tous et dans les ténèbres les former"
requirement = ["Médaille en argent"]
